name: CI Runner
permissions:
  checks: write
  actions: read
  contents: read
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 9 4 10 *' # 9AM 10/4 UTC, 2AM 10/4 PT
jobs:
  run-autograding-tests:
    runs-on: self-hosted
    container: ghcr.io/sfu-cmpt-201/runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grader
        uses: SFU-CMPT-201/graders/.github/actions/a7@main
      - name: Autograding Reporter
        uses: SFU-CMPT-201/autograding-grading-reporter@v1
      - name: Clean up
        run: |
          rm -rf ./* ./.* > /dev/null 2>&1 || true
        if: ${{ always() }}
